# Override these settings with your own
baseURL = "https://example.org/"
languageCode = "en-us"
copyright = "© {year}"

# The value "hugo-theme-codex" is only to get the exampleSite
# to work in this repo. Change to whatever name you gave the theme
# when you added it. If you followed the README, you should have 
# added the theme using the name "codex".
theme = "codex" 

# Add your Disqus shortname here.
# disqusShortname = ""

# Add your Google Analytics identifier: UA-XXXXXXXX-X
# googleAnalytics = "" 

# Optional params
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  # twitter = "https://twitter.com/<your handle>"
  github = "https://github.com/ElasticBottle"
  # email = "mailto:<your email>"
  # facebook = "https://facebook.com/<your handle>"
  # gitlab = "https://gitlab.com/<your handle>"
  # instagram = "https://instagram.com/<your handle>"
  # linkedin = "<link to your profile>"
  # youtube = "https://www.youtube.com/channel/<your channel>"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconTitles = ["GitHub"]

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    # style = "monokai"
    # lineNoStart = 1
    # lineNos = true

    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "About"
  name = "About"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "Blog"
  name = "Blog"
  title = "Blog"
  url = "/blog"



